### ISSUE TITLE
Cannot use INITIUM_LB_ENDPOINT with Rancher

### ISSUE THREAD

**Issue by LucaLanziani** [nearform/initium-platform#194]
On certain setups (Rancher Desktop on Mac M1) the docker network connectivity seems broken and so the INITIUM_LB_ENDPOINT used in the quickstart will not work.

We should change the quick-start to have an extra step right before the curl that gives two options.

1. INITIUM_LB_ENDPOINT if the docker network works
2. Use port forwarding with `kubectl port-forward service/istio-ingressgateway -n istio-ingress 8080:80` and export INITIUM_LB_ENDPOINT as 127.0.0.1:8080

**Comment by spchortis** [comment]
As part of quick start validation LB endpoint was updated in the guide. [This](https://github.com/nearform/initium/pull/13) one added it.
